name: Go CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.6'

      - name: Download dependencies
        run: go mod tidy

      - name: Run tests with verbose output and coverage
        run: |
          mkdir -p coverage
          go test ./... -v -race -coverprofile=coverage/coverage.out -covermode=atomic
          go tool cover -func=coverage/coverage.out | tee coverage/coverage.txt
          go tool cover -html=coverage/coverage.out -o coverage/coverage.html

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/

      - name: Print coverage summary
        run: cat coverage/coverage.txt
